# Generated by Django 3.2.9 on 2021-12-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211213_2142'),
        ('checkout', '0006_alter_orderlineitem_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='productsize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
