# Generated by Django 3.2.9 on 2021-12-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_orderlineitem_productsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
