# Generated by Django 3.2 on 2022-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='productprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
