# Generated by Django 3.2.9 on 2021-12-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Variation',
            new_name='ProductVariation',
        ),
    ]
