# Generated by Django 3.2.9 on 2021-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariation_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='product_size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='baseprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
