# Generated by Django 3.2 on 2021-12-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseprice',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
