# Generated by Django 3.2 on 2021-12-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_baseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baseprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
