# Generated by Django 3.2 on 2022-01-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0010_reviewrating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRating',
            new_name='Review',
        ),
    ]
