# Generated by Django 3.2 on 2022-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20220115_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
